# Generated by Django 5.1.3 on 2024-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_model',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
